package prog2.midgroup01;

import javax.swing.*;
import java.awt.*;
import javax.swing.text.*;


public class GUI extends javax.swing.JFrame {

    JTextField textfield;
    JLabel label;
    /**
     * Creates new form NewJFrame
     */
    public GUI() {
        new UserGuide();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        //initialize the components of the GUI
        jPanel1 = new javax.swing.JPanel();
        jfraction2label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fraction1label = new java.awt.Label();
        f1DentextField = new java.awt.TextField();
        f1NumtextField = new java.awt.TextField();
        fraction2label = new java.awt.Label();
        f2NumtextField = new java.awt.TextField();
        f2DentextField = new java.awt.TextField();
        f2WholetextField = new java.awt.TextField();
        f1WholetextField = new java.awt.TextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        computeButton = new java.awt.Button();
        clearButton = new java.awt.Button();
        jequalsSign = new javax.swing.JLabel();
        resultWholetextField = new java.awt.TextField();
        resultLabel = new java.awt.Label();
        resultNumtextField = new java.awt.TextField();
        resultDentextField = new java.awt.TextField();


        //sets location of the window
        setLocation(500, 200);

        setResizable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        //initializes the background color of the window
        setBackground(new java.awt.Color(253, 202, 64));
        //sets the background of the container that contains the header
        jPanel1.setBackground(new java.awt.Color(253, 202, 64));

        //Sets the size, font style and the title of the header
        jfraction2label.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jfraction2label.setText("Fraction Calculator");

        //Creates the layout for the container of the header
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);

        //horizontal alignment for the components inside the container
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jfraction2label)
                                .addGap(259, 259, 259))
        );

        //vertical alignment for the components inside the container
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jfraction2label)
                                .addGap(106, 106, 106))
        );

        //Sets the background color of the container below the header
        jPanel2.setBackground(new java.awt.Color(254, 238, 194));
        //Adds the specified mouse listener to receive mouse events from this container.
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        //setting the size and font style of the font for the label of the following components:
        //FRACTION 1 LABEL
        fraction1label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fraction1label.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        fraction1label.setText("Fraction 1");

        // FRACTION 1 DENOMINATOR TEXT FIELD
        f1DentextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        f1DentextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1DentextFieldActionPerformed(evt);
            }
        });

        //FRACTION 1 NUMERATOR TEXT FILED
        f1NumtextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        f1NumtextField.setForeground(new java.awt.Color(0,0,0));
        f1NumtextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1NumtextFieldActionPerformed(evt);
            }
        });

        //FRACTION 1 WHOLE NUMBER TEXT FIELD
        f1WholetextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        f1WholetextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1WholetextFieldActionPerformed(evt);
            }
        });

        // FRACTION 2 LABEL
        fraction2label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fraction2label.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        fraction2label.setText("Fraction 2");

        //FRACTION 2 NUMERATOR TEXT FIELD
        f2NumtextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        f2NumtextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2NumtextFieldActionPerformed(evt);
            }
        });

        //FRACTION 2 DENOMINATOR TEXT FIELD
        f2DentextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        f2DentextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2DentextFieldActionPerformed(evt);
            }
        });

        //FRACTION 2 WHOLE NUMBER TEXT FIELD
        f2WholetextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        f2WholetextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2WholetextFieldActionPerformed(evt);
            }
        });

        //DROP DOWN BOX FOR THE OPERATORS
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/" }));

        //Compute button to perform arithmetic operations on the fractions
        computeButton.setLabel("Compute");
        computeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeButtonActionPerformed(evt);
            }
        });

        //CLEAR BUTTON to clear the input in the text fields
        clearButton.setLabel("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        //EQUAL SIGN LABEL
        jequalsSign.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jequalsSign.setText("=");

        //ANSWER WHOLE NUMBER TEXT FIELD
        resultWholetextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        resultWholetextField.setEditable(false);
        resultWholetextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultWholetextFieldActionPerformed(evt);
            }
        });

        //RESULT LABEL
        resultLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resultLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        resultLabel.setText("Result");

        // RESULT NUMERATOR TEXT FILED
        resultNumtextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        resultNumtextField.setEditable(false);
        resultNumtextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultNumtextFieldActionPerformed(evt);
            }
        });

        //RESULT DENOMINATOR TEXT FIELD
        resultDentextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        resultDentextField.setEditable(false);
        resultDentextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultDentextFieldActionPerformed(evt);
            }
        });

        //  Creates a group layout for the container that contains the rest of the elements in the frame, such as the text fields, labels, and buttons
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);

        // sets layout for the second container
        jPanel2.setLayout(jPanel2Layout);

        //Sets the horizontal alignment of the  components inside the container
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(152, 152, 152)
                                                .addComponent(f1WholetextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(fraction1label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(f1DentextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(f1NumtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(19, 19, 19)
                                                                .addComponent(f2WholetextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(100, 100, 100)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(fraction2label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(157, 157, 157))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(f2NumtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(f2DentextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(68, 68, 68)
                                                                .addComponent(jequalsSign)
                                                                .addGap(30, 30, 30)
                                                                .addComponent(resultWholetextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(resultNumtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(resultDentextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(115, 115, 115)
                                                                .addComponent(computeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap(158, Short.MAX_VALUE)))));


        //Sets the vertical alignment of the  components inside the container
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(fraction2label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(f2NumtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(f2DentextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addComponent(f2WholetextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(64, 64, 64)
                                                                .addComponent(jequalsSign, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(fraction1label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(f1NumtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(f1DentextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addComponent(f1WholetextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(resultNumtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(resultDentextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addComponent(resultWholetextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(computeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(156, Short.MAX_VALUE)));


        //Creates the group layout of th frame itself which arranges the containers inside it
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        //Sets the horizontal alignment of the containers inside the frame
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        //Sets the vertical alignment of the containers inside the frame
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>
    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void f1DentextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void f1NumtextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void f2NumtextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void f2DentextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void f2WholetextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void f1WholetextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void computeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        // assigns user input to th following variables
        String num1Str= f1NumtextField.getText();
        String den1Str= f1DentextField.getText();
        String whole1Str= f1WholetextField.getText();
        String num2Str= f2NumtextField.getText();
        String den2Str= f2DentextField.getText();
        String whole2Str= f2WholetextField.getText();
        String operator= (String) jComboBox1.getSelectedItem();

        try { // convert user input strings to numbers,
            // Performs the calculation based on the selected operator, and
            // Handles potential division by zero errors
            int f1Num= Integer.parseInt(num1Str);
            int f1Den= Integer.parseInt(den1Str);
            int f1Whole= Integer.parseInt(whole1Str);
            int f2Num= Integer.parseInt(num2Str);
            int f2Den= Integer.parseInt(den2Str);
            int f2Whole= Integer.parseInt(whole2Str);

            // stores user input
            MixedFraction fraction1= new MixedFraction(f1Whole, f1Num, f1Den);
            MixedFraction fraction2= new MixedFraction(f2Whole, f2Num, f2Den);


            MixedFraction sum= fraction1.add(fraction2);
            MixedFraction dif= fraction1.subtract(fraction2);
            MixedFraction quotient= fraction1.divideBy(fraction2);
            MixedFraction product = fraction1.multiplyBy(fraction2);

            MixedFraction result = new MixedFraction();

            switch (operator) {
                case "+":
                    result= sum;
                    break;
                case "-":
                    result= dif;
                    break;
                case "*":
                    result = product;
                    break;
                case "/":
                    result = quotient;
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Invalid operator!");
                    return;
            }


            // displays answer to the output box

            //if  the numerator or the denominator is zero
            if ((result.getNumerator()* result.getDenominator()) == 0) {
                resultWholetextField.setText(""+result.getWhole());
                resultNumtextField.setText("");
                resultDentextField.setText("");
            } else {
                // if whole number is zero
                if (result.getWhole() == 0) {
                    resultWholetextField.setText("");
                    resultNumtextField.setText("" + result.getNumerator());
                    resultDentextField.setText("" + result.getDenominator());
                }else {
                    resultWholetextField.setText(""+result.getWhole());
                    resultNumtextField.setText(""+result.getNumerator());
                    resultDentextField.setText(""+result.getDenominator());

                }

            }


            // shows another window for the results
            JOptionPane.showMessageDialog(null, "Hello!"+ "The result is: \n" + result.toString()+" or "+ result.toDouble() +
                     "\nFraction 1: "+ fraction1.toString()+"\nFraction 2: "+ fraction2.toString());


        } catch (NumberFormatException numEx) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers!", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (ArithmeticException ariEx) {
            JOptionPane.showMessageDialog(null, "Zero (0) cannot be a denominator! \nPlease try again.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Oh no! It seems like we have encountered an error. \nPlease try again.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // clears the input inside the tex field
        f1NumtextField.setText("");
        f1DentextField.setText("");
        f1WholetextField.setText("");
        f2NumtextField.setText("");
        f2DentextField.setText("");
        f2WholetextField.setText("");
        resultNumtextField.setText("");
        resultDentextField.setText("");
        resultWholetextField.setText("");
    }
    private void resultWholetextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void resultNumtextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void resultDentextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private java.awt.Button computeButton;
    private java.awt.Button clearButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jfraction2label;
    private javax.swing.JLabel jequalsSign;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label fraction1label;
    private java.awt.Label fraction2label;
    private java.awt.Label resultLabel;
    private java.awt.TextField f1DentextField;
    private java.awt.TextField resultNumtextField;
    private java.awt.TextField resultDentextField;
    private java.awt.TextField f1NumtextField;
    private java.awt.TextField f2NumtextField;
    private java.awt.TextField f2DentextField;
    private java.awt.TextField f2WholetextField;
    private java.awt.TextField f1WholetextField;
    private java.awt.TextField resultWholetextField;
    // End of variables declaration
}
